In [137]:


import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression


df=pd.read_csv('diabetes.csv')

In [138]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [139]:
df.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [141]:
df.sample()

     Pregnancies  Glucose  ...  Age  Outcome
107            4      144  ...   37        0

[1 rows x 9 columns]

In [142]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [143]:

print(df.isnull())

     Pregnancies  Glucose  ...    Age  Outcome
0          False    False  ...  False    False
1          False    False  ...  False    False
2          False    False  ...  False    False
3          False    False  ...  False    False
4          False    False  ...  False    False
..           ...      ...  ...    ...      ...
763        False    False  ...  False    False
764        False    False  ...  False    False
765        False    False  ...  False    False
766        False    False  ...  False    False
767        False    False  ...  False    False

[768 rows x 9 columns]

In [144]:
df.mean(numeric_only = True)

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [145]:
df.corr(numeric_only= True)

                          Pregnancies   Glucose  ...       Age   Outcome
Pregnancies                  1.000000  0.129459  ...  0.544341  0.221898
Glucose                      0.129459  1.000000  ...  0.263514  0.466581
BloodPressure                0.141282  0.152590  ...  0.239528  0.065068
SkinThickness               -0.081672  0.057328  ... -0.113970  0.074752
Insulin                     -0.073535  0.331357  ... -0.042163  0.130548
BMI                          0.017683  0.221071  ...  0.036242  0.292695
DiabetesPedigreeFunction    -0.033523  0.137337  ...  0.033561  0.173844
Age                          0.544341  0.263514  ...  1.000000  0.238356
Outcome                      0.221898  0.466581  ...  0.238356  1.000000

[9 rows x 9 columns]

In [146]:
df.isnull()

     Pregnancies  Glucose  ...    Age  Outcome
0          False    False  ...  False    False
1          False    False  ...  False    False
2          False    False  ...  False    False
3          False    False  ...  False    False
4          False    False  ...  False    False
..           ...      ...  ...    ...      ...
763        False    False  ...  False    False
764        False    False  ...  False    False
765        False    False  ...  False    False
766        False    False  ...  False    False
767        False    False  ...  False    False

[768 rows x 9 columns]

In [147]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [148]:
missing = df[df.isnull().any(axis=1)]
missing

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [149]:
index=df.columns[df.isnull().any(axis=0)]
index

Index([], dtype='object')

In [150]:
df[index]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[768 rows x 0 columns]

In [151]:
#Handling the missing values
#bfill and ffill
#dropna
#mean
#median
#mode

ffill_data = df.ffill()
ffill_data

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [152]:
d2 = df.bfill()
d2

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [172]:
X = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 
        'Insulin', 'BMI', 'DiabetesPedigreeFunction']]


y = df[['Outcome']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

print("X_train values:\n", X_train.head())
print("X_test values:\n", X_test.head())
print("y_train values:\n", y_train.head())
print("y_test values:\n", y_test.head())

X_train values:
      Pregnancies  Glucose  ...   BMI  DiabetesPedigreeFunction
762            9       89  ...  22.5                     0.142
127            1      118  ...  33.3                     0.261
564            0       91  ...  32.4                     0.601
375           12      140  ...  39.2                     0.528
663            9      145  ...  37.9                     0.637

[5 rows x 7 columns]
X_test values:
      Pregnancies  Glucose  ...   BMI  DiabetesPedigreeFunction
661            1      199  ...  42.9                     1.394
122            2      107  ...  33.6                     0.404
113            4       76  ...  34.0                     0.391
14             5      166  ...  25.8                     0.587
529            0      111  ...  24.6                     0.660

[5 rows x 7 columns]
y_train values:
      Outcome
762        0
127        0
564        0
375        1
663        1
y_test values:
      Outcome
661        1
122        0
113        0
14         1
529        0

In [174]:

#regressor = LinearRegression()

#X_train = np.array(X_train).reshape(-1,1)
#regressor.fit(X_train,y_train)

In [155]:
# Predicting the Test set results

In [175]:
#y_pred = regressor.predict(X_test)
#y_pred.reshape(-1,1)

In [176]:
#r_sq = regressor.score(X,y)
#r_sq

In [177]:
#x = np.array([[12.5]])
#predicted = regressor.predict(x)
#predicted

In [159]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [160]:
# Separate the independent  (X) and dependent (y) variables

X = df.iloc[:, :-1].values #all colimns except last column
y = df.iloc[:, -1].values #outcome columns
X[:5] #

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01]])

In [161]:
#feature scaling(optional but improves model convergence)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

array([[-1.01521454],
       [-0.09964691],
       [-0.95207195],
       [ 0.59492164],
       [ 0.75277813],
       [ 1.03691981],
       [-0.60478767],
       [-0.69950156],
       [-0.32064599],
       [ 0.56335034],
       [-0.57321637],
       [ 0.46863645],
       [-0.2575034 ],
       [-1.39407011],
       [-0.82578675],
       [-0.69950156],
       [ 1.06849111],
       [ 0.08978088],
       [-0.82578675],
       [-1.04678584],
       [-0.28907469],
       [ 0.94220592],
       [-0.28907469],
       [-1.26778492],
       [-0.06807561],
       [ 0.31077996],
       [ 1.25791889],
       [-0.79421546],
       [-0.82578675],
       [-0.63635897],
       [ 0.21606607],
       [ 0.40549385],
       [ 0.81592072],
       [ 0.59492164],
       [-0.54164508],
       [-0.38378859],
       [-0.82578675],
       [-0.47850248],
       [ 0.02663828],
       [ 0.94220592],
       [-1.20464233],
       [ 0.02663828],
       [ 0.78434943],
       [ 0.05820958],
       [-0.54164508],
       [ 0.97377721],
       [-0.66793027],
       [ 1.54206057],
       [-1.04678584],
       [ 0.34235126],
       [-0.2575034 ],
       [-0.38378859],
       [-0.92050065],
       [-0.66793027],
       [-0.98364324],
       [ 0.56335034],
       [-0.60478767],
       [ 1.163205  ],
       [-0.44693118],
       [ 0.75277813],
       [-0.98364324],
       [ 0.21606607],
       [-0.51007378],
       [ 1.32106149],
       [ 0.15292347],
       [-0.66793027],
       [-0.82578675],
       [-0.13121821],
       [-0.95207195],
       [-0.88892935],
       [-0.76264416],
       [ 0.02663828],
       [-0.32064599],
       [-2.05706736],
       [-0.66793027],
       [ 1.98405874],
       [-0.1943608 ],
       [-1.36249882],
       [-0.2259321 ],
       [-1.67821179],
       [-1.14149973],
       [-0.06807561],
       [ 0.46863645],
       [ 0.12135218],
       [-1.29935622],
       [-0.00493302],
       [ 0.50020775],
       [-1.45721271],
       [-1.14149973],
       [ 1.51048927],
       [ 0.05820958],
       [-0.32064599],
       [-0.66793027],
       [-0.32064599],
       [-1.29935622],
       [-1.17307103],
       [-1.14149973],
       [ 0.75277813],
       [ 1.54206057],
       [ 0.02663828],
       [-1.33092752],
       [ 0.68963553],
       [-0.60478767],
       [ 2.39448561],
       [ 2.36291431],
       [-1.20464233],
       [-0.92050065],
       [-0.03650431],
       [-0.47850248],
       [ 1.28949019],
       [-0.44693118],
       [-0.63635897],
       [ 0.27920866],
       [ 0.84749202],
       [ 0.78434943],
       [ 0.40549385],
       [ 0.27920866],
       [-1.29935622],
       [ 0.72120683],
       [-1.17307103],
       [-0.92050065],
       [ 0.65806424],
       [-0.2259321 ],
       [ 0.12135218],
       [-1.20464233],
       [ 0.59492164],
       [ 2.29977172],
       [ 0.12135218],
       [ 0.02663828],
       [ 0.15292347],
       [-1.48878401],
       [-1.04678584],
       [-0.66793027],
       [ 2.14191523],
       [ 0.68963553],
       [-0.28907469],
       [-0.66793027],
       [ 0.81592072],
       [ 2.14191523],
       [ 0.53177905],
       [ 0.59492164],
       [ 0.56335034],
       [-1.01521454],
       [-0.79421546],
       [ 1.1316337 ],
       [-0.98364324],
       [ 1.88934485],
       [-0.69950156],
       [ 0.94220592],
       [ 0.21606607],
       [ 0.43706515],
       [ 1.95248744],
       [ 0.72120683],
       [-1.07835714],
       [ 0.21606607],
       [-0.09964691],
       [ 1.98405874],
       [ 1.85777355],
       [ 0.37392256],
       [ 0.65806424],
       [ 0.08978088],
       [-0.03650431],
       [-1.26778492],
       [ 0.75277813],
       [ 0.43706515],
       [ 0.31077996],
       [-0.41535989],
       [-1.01521454],
       [ 2.07877263],
       [ 0.05820958],
       [ 0.15292347],
       [-0.69950156],
       [-0.66793027],
       [-0.03650431],
       [ 1.06849111],
       [-0.00493302],
       [-0.41535989],
       [ 1.79463095],
       [ 0.81592072],
       [-0.88892935],
       [-1.17307103],
       [-0.1943608 ],
       [-3.82506003],
       [ 1.47891798],
       [ 0.08978088],
       [-0.85735805],
       [-1.10992843],
       [ 2.29977172],
       [ 0.27920866],
       [-0.98364324],
       [-0.03650431],
       [ 1.00534851],
       [ 0.91063462],
       [-0.38378859],
       [ 0.94220592],
       [-0.82578675],
       [ 1.32106149],
       [-0.63635897],
       [-0.60478767],
       [-0.32064599],
       [ 1.82620225],
       [-0.28907469],
       [ 2.07877263],
       [-1.17307103],
       [-3.82506003],
       [-0.82578675],
       [ 0.62649294],
       [ 0.05820958],
       [ 0.24763737],
       [ 0.84749202],
       [-0.79421546],
       [ 1.41577538],
       [ 1.85777355],
       [-0.03650431],
       [-0.03650431],
       [-0.98364324],
       [-0.54164508],
       [ 0.27920866],
       [ 0.34235126],
       [ 1.44734668],
       [ 0.87906332],
       [ 1.41577538],
       [-0.95207195],
       [-0.66793027],
       [-0.2575034 ],
       [ 2.11034393],
       [-0.13121821],
       [-0.51007378],
       [ 0.12135218],
       [ 0.91063462],
       [ 1.63677446],
       [-0.79421546],
       [ 0.02663828],
       [ 0.34235126],
       [-0.47850248],
       [ 1.88934485],
       [-0.2259321 ],
       [-1.04678584],
       [-0.63635897],
       [ 2.07877263],
       [-0.88892935],
       [ 0.12135218],
       [ 1.163205  ],
       [-1.10992843],
       [ 0.18449477],
       [-0.28907469],
       [-0.47850248],
       [ 0.21606607],
       [-1.33092752],
       [ 0.37392256],
       [ 2.42605691],
       [-0.69950156],
       [ 0.24763737],
       [ 0.50020775],
       [-0.13121821],
       [ 0.81592072],
       [-1.70978309],
       [ 1.63677446],
       [-0.95207195],
       [-0.1627895 ],
       [-0.47850248],
       [-0.57321637],
       [ 0.12135218],
       [-0.2259321 ],
       [ 1.1000624 ],
       [ 0.24763737],
       [ 2.36291431],
       [-0.00493302],
       [-0.47850248],
       [-0.41535989],
       [-0.63635897],
       [-0.85735805],
       [ 1.66834576],
       [ 0.24763737],
       [-0.06807561],
       [ 1.76305965],
       [ 0.24763737],
       [ 0.24763737],
       [-0.44693118],
       [-1.17307103],
       [ 1.28949019],
       [-1.48878401],
       [-0.00493302],
       [ 2.14191523],
       [ 0.05820958],
       [ 1.69991706],
       [-0.38378859],
       [-0.51007378],
       [ 0.94220592],
       [-1.26778492],
       [ 1.35263278],
       [-0.88892935],
       [-0.95207195],
       [ 0.18449477],
       [ 2.14191523],
       [ 2.04720133],
       [ 0.27920866],
       [ 1.163205  ],
       [ 0.05820958],
       [ 0.08978088],
       [ 0.08978088],
       [-0.00493302],
       [ 0.31077996],
       [-0.79421546],
       [-0.09964691],
       [ 0.62649294],
       [ 0.72120683],
       [ 0.12135218],
       [ 1.35263278],
       [ 0.15292347],
       [-0.98364324],
       [-1.01521454],
       [-0.76264416],
       [-0.51007378],
       [ 0.50020775],
       [ 1.163205  ],
       [ 2.33134301],
       [ 0.15292347],
       [-0.73107286],
       [ 0.05820958],
       [-1.36249882],
       [ 0.40549385],
       [ 0.56335034],
       [-0.63635897],
       [ 1.82620225],
       [-0.63635897],
       [ 0.53177905],
       [ 0.15292347],
       [-0.35221729],
       [-0.09964691],
       [ 0.08978088],
       [ 0.24763737],
       [ 0.78434943],
       [-0.69950156],
       [-0.03650431],
       [ 0.27920866],
       [ 1.163205  ],
       [ 0.40549385],
       [-2.02549607],
       [-0.41535989],
       [-0.13121821],
       [ 1.22634759],
       [-1.17307103],
       [-0.28907469],
       [-1.14149973],
       [-0.35221729],
       [-0.1627895 ],
       [-0.73107286],
       [ 1.28949019],
       [ 1.03691981],
       [-0.47850248],
       [-0.57321637],
       [ 0.56335034],
       [-0.66793027],
       [-0.66793027],
       [-0.57321637],
       [-0.92050065],
       [ 1.1000624 ],
       [-1.36249882],
       [-0.2259321 ],
       [-0.44693118],
       [-1.33092752],
       [-0.92050065],
       [ 0.46863645],
       [ 1.1947763 ],
       [-0.82578675],
       [ 0.37392256],
       [-0.47850248],
       [ 0.84749202],
       [-0.82578675],
       [-0.73107286],
       [ 1.163205  ],
       [ 0.15292347],
       [ 0.24763737],
       [-0.1627895 ],
       [ 0.31077996],
       [ 0.21606607],
       [ 1.06849111],
       [-0.44693118],
       [ 1.1316337 ],
       [ 0.12135218],
       [ 0.24763737],
       [-0.92050065],
       [-0.85735805],
       [ 0.24763737],
       [ 1.82620225],
       [ 1.44734668],
       [-0.98364324],
       [-0.1943608 ],
       [ 0.24763737],
       [-1.48878401],
       [-0.38378859],
       [ 0.68963553],
       [-0.51007378],
       [-0.38378859],
       [-0.51007378],
       [-3.82506003],
       [ 1.06849111],
       [ 0.84749202],
       [ 1.28949019],
       [-0.76264416],
       [-0.2259321 ],
       [-0.47850248],
       [-0.13121821],
       [-0.28907469],
       [ 1.47891798],
       [-1.07835714],
       [-0.06807561],
       [ 1.03691981],
       [ 0.02663828],
       [-0.32064599],
       [ 0.27920866],
       [ 2.39448561],
       [ 2.11034393],
       [ 1.85777355],
       [-1.36249882],
       [-0.1943608 ],
       [ 0.12135218],
       [ 1.57363187],
       [-0.98364324],
       [ 1.1000624 ],
       [-0.13121821],
       [-1.5834979 ],
       [ 1.63677446],
       [-0.51007378],
       [ 2.20505782],
       [ 0.97377721],
       [ 0.59492164],
       [ 0.08978088],
       [-1.23621362],
       [-0.60478767],
       [-0.92050065],
       [-0.1943608 ],
       [-0.60478767],
       [ 0.78434943],
       [ 0.78434943],
       [-0.63635897],
       [ 0.65806424],
       [ 1.32106149],
       [ 0.78434943],
       [ 1.06849111],
       [-1.5203553 ],
       [-0.1627895 ],
       [-0.13121821],
       [ 0.62649294],
       [-0.09964691],
       [ 1.38420408],
       [ 0.81592072],
       [-0.66793027],
       [-0.85735805],
       [-3.82506003],
       [-1.04678584],
       [-0.2575034 ],
       [ 0.50020775],
       [ 1.47891798],
       [ 1.57363187],
       [-0.47850248],
       [ 0.53177905],
       [ 0.78434943],
       [ 0.37392256],
       [-0.28907469],
       [-1.07835714],
       [ 1.98405874],
       [ 0.81592072],
       [ 0.05820958],
       [ 0.34235126],
       [ 0.68963553],
       [-0.88892935],
       [-1.07835714],
       [ 1.63677446],
       [-0.06807561],
       [-0.32064599],
       [ 0.08978088],
       [ 1.63677446],
       [-0.95207195],
       [-0.98364324],
       [ 0.53177905],
       [-1.26778492],
       [-1.17307103],
       [-0.47850248],
       [-0.51007378],
       [ 0.21606607],
       [-0.32064599],
       [ 1.88934485],
       [-0.44693118],
       [ 0.72120683],
       [-0.69950156],
       [ 2.17348652],
       [-0.32064599],
       [-0.38378859],
       [-0.03650431],
       [ 0.12135218],
       [-0.51007378],
       [ 1.28949019],
       [ 1.28949019],
       [-0.41535989],
       [-1.07835714],
       [ 0.02663828],
       [-0.92050065],
       [-1.5834979 ],
       [-0.28907469],
       [-0.69950156],
       [ 0.50020775],
       [ 0.21606607],
       [-0.82578675],
       [ 1.66834576],
       [-1.23621362],
       [ 0.05820958],
       [-1.20464233],
       [-0.69950156],
       [-0.69950156],
       [-0.44693118],
       [-0.66793027],
       [-0.28907469],
       [-0.2259321 ],
       [ 0.62649294],
       [-0.13121821],
       [-0.47850248],
       [-1.67821179],
       [ 0.72120683],
       [ 1.38420408],
       [-1.5834979 ],
       [-0.69950156],
       [-0.1627895 ],
       [ 1.73148836],
       [-0.41535989],
       [-0.13121821],
       [ 0.75277813],
       [-1.5203553 ],
       [ 0.40549385],
       [-1.17307103],
       [ 2.33134301],
       [-0.2259321 ],
       [ 0.78434943],
       [-0.60478767],
       [-1.17307103],
       [-1.04678584],
       [-0.66793027],
       [-0.69950156],
       [-0.79421546],
       [-0.79421546],
       [-0.1943608 ],
       [-0.47850248],
       [-1.29935622],
       [ 0.24763737],
       [ 0.02663828],
       [-0.54164508],
       [-1.01521454],
       [-0.88892935],
       [ 0.78434943],
       [ 0.15292347],
       [-2.02549607],
       [-0.88892935],
       [ 1.88934485],
       [-1.45721271],
       [-0.66793027],
       [-1.17307103],
       [ 0.56335034],
       [-1.29935622],
       [-0.38378859],
       [-0.79421546],
       [-0.41535989],
       [-0.06807561],
       [-0.66793027],
       [-0.38378859],
       [ 1.03691981],
       [-0.54164508],
       [-0.13121821],
       [ 0.12135218],
       [ 2.36291431],
       [ 0.18449477],
       [-0.63635897],
       [ 1.1947763 ],
       [-0.85735805],
       [-1.14149973],
       [ 0.46863645]])

In [162]:
#Train the logistic regression model

classifier = LogisticRegression()
classifier.fit(X_train, y_train)

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [163]:
#Predict test results

y_pred = classifier.predict(X_test)
print(y_pred, y_test)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0
 0 0 0 1 0 0 0]      Outcome
661        1
122        0
113        0
14         1
529        0
..       ...
366        1
301        1
382        0
140        0
463        0

[192 rows x 1 columns]

In [164]:
#Evaluate model performance

cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))

[[116  14]
 [ 31  31]]
Accuracy: 0.765625

In [186]:
#Predict for a new sample

new_data = np.array([[150]])  # Only Glucose value
new_sc = sc.fit_transform(new_data)
prediction1 = classifier.predict(new_sc)
print("Prediction:", prediction1)

Prediction: [0]

In [189]:
new_data = np.array([[32.1]])  # Only Glucose value
new_sc = sc.fit_transform(new_data)
prediction1 = classifier.predict(new_sc)
print("Prediction:", prediction1)

Prediction: [0]

In [190]:
from sklearn.datasets import load_wine

In [191]:
df = load_wine()

In [192]:
df = pd.DataFrame(df.data, columns = df.feature_names)

In [193]:
df

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]